sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: localhost:8080
    access-key-secret: 123456
    access-key-id: 1
    bucket-name: files

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

  wx:
    appid: wxf59e1834799d563b
    secret: 3eaf64146458c69be392d7b4a16c18b0
